server.port : 5000

#
# Health check configuration
#
management:
  endpoint:
    health:
      show-details: always

#
# Spring configuration
#
spring:
  application.name: events-time

  #
  # Datasource
  #
  datasource:
    driver-class-name: org.postgresql.Driver
    # It shall be configured via AWS Parameter Store - /di/config/spring.datasource.url
    url: jdbc:postgresql://localhost:5432/events_time?stringtype=unspecified
    # It shall be configured via AWS Secret Manager - /di/config/datasource
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 60000
      idle-timeout: 300000
      validation-timeout: 30000
      leak-detection-threshold: 60000

  data.jpa.repositories.enabled: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: false
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties.hibernate:
      format_sql: false
      jdbc:
        batch_size: 100
        time_zone: UTC
      dialect.storage_engine: innodb
      query:
        plan_cache_max_size: 16
        plan_parameter_metadata_max_size: 128

  ## MULTIPART (MultipartProperties)
  servlet:
    multipart:
      # Enable multipart uploads
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB

  #
  # Liquibase Support
  #
  liquibase:
    change-log: classpath:db/liquibase-include-all.yaml
    database-change-log-table: liq_db_changelog
    database-change-log-lock-table: liq_db_changelog_lock

cloud:
  aws:
    region.static: us-east-1
    s3.endpoint: http://s3.localhost.localstack.cloud:4566
    credentials:
      access-key: test
      secret-key: test

server:
  error:
    include-message: always

jwt:
  access-token:
    secret-key: ======================access=token=spring===========================
    expiration-time-seconds: 86400
  refresh-token:
    secret-key: ======================refresh=token=spring===========================
    expiration-time-days: 180

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

events-time:
  ## File Storage Properties
  s3:
    bucket: events-time-local

# Log configuration
#
logging.level:
  # Log fetched parameters from AWS
  io.awspring.cloud.paramstore.AwsParamStorePropertySource: debug
