version: '3'
services:
  postgres_service:
    image: postgres:13-alpine
    networks:
      - m7-network
    container_name: postgres_service
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=events_time
      - TZ=UTC
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ../src/main/resources/db/changelog/202308282104-changelog.sql:/docker-entrypoint-initdb.d/202308282104-changelog.sql
      - ./postgres/liquibase_version.sql:/docker-entrypoint-initdb.d/liquibase_version.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-init:
    image: postgres:13-alpine
    networks:
      - m7-network
    environment:
      - DATASOURCE_URL=postgres_service
      - PGPASSWORD=postgres
    depends_on:
      postgres_service:
        condition: service_healthy
    volumes:
      - ../src/main/resources/db/seed/initial_load.sql:/tmp/initial_load.sql
    command: bash -c "sleep 10 && psql -h $$DATASOURCE_URL -U postgres -d events_time -f /tmp/initial_load.sql"

networks:
  m7-network:
    driver: bridge
