version: '3'
services:
  postgres:
    image: 'postgres:13-alpine'
    networks:
      - m7-network
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=events_time
      - TZ=UTC
    ports:
      - "5432:5432"
    volumes:
      - $HOME/docker/volumes/postgres/data:/var/lib/postgresql/data

networks:
  m7-network:
    driver: bridge
