package io.eventstime.exception

enum class ConfigErrorType {
    UNAUTHORIZED,
    INTERNAL_SERVER_ERROR,
    OTA_SETUP_FILE_NOT_FOUND,
    OTA_SETUP_FILE_ALREADY_DEPRECATED,
    OTA_SETUP_FILE_ALREADY_DELETED,
    OTA_SETUP_FILE_ALREADY_ACTIVE,
    CANNOT_REACTIVATE_DELETED_OTA_SETUP_FILE,
    OTA_SETUP_FILE_ALREADY_EXISTS,
    FILE_EXTENSION_NOT_ALLOWED,
    INVALID_HASH,
    MISSING_FIELD,
    FORBIDDEN_OTA
}
